[tool.poetry]
name = "nonebot_plugin_nowtime"
version = "0.1.0"
description = "Nonebot2 plugin for telling the time per hour"
authors = ["Cvadia"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Cvandia/nonebot_plugin_nowtime"
repository = "https://github.com/Cvandia/nonebot_plugin_nowtime"

[tool.poetry.dependencies]
python = "^3.8"
nonebot2 = "^2.0.0-beta.4"
nonebot-adapter-onebot = "^2.1.1"
httpx = ">=0.19.0"
Pillow = "^9.0.0"
nonebot-plugin-apscheduler= "^0.2.0"

[tool.poetry.dev-dependencies]
nb-cli = "^0.6.0"
black = "^22.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"